import React from "react";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import localFont from "next/font/local";
import "@/styles/globals.css";

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "900"],
});

const georgia = localFont({
  src: [
    {
      path: "../fonts/Georgia.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/Georgia Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../fonts/Georgia Bold.ttf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../fonts/Georgia Bold Italic.ttf",
      weight: "900",
      style: "italic",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: {
      type: "image/png",
      sizes: "32x32",
      url: "/favicon/favicon-32x32.png",
    },
    other: [
      {
        rel: "icon",
        type: "image/png",
        url: "/favicon/favicon-16x16.png",
        sizes: "16x16",
      },
      {
        rel: "apple-touch-icon",
        url: "/favicon/apple-touch-icon.png",
        sizes: "180x180",
      },
    ],
  },
  manifest: "/favicon/site.webmanifest",
  stylesheet: "https://fonts.googleapis.com/css?family=Lato:300,400,400i,700",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      className="bg-material-dark text-material-white break-words"
    >
      <body className="subpixel-antialiased">{children}</body>
    </html>
  );
}
